## K Fold CrossValidation on DIGITS DATASET

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(digits.data, digits.target, test_size = 0.3)

In [4]:
lr = LogisticRegression()
lr.fit(xtrain, ytrain)
lr.score(xtest, ytest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [5]:
sv = SVC()
sv.fit(xtrain, ytrain)
sv.score(xtest, ytest)

0.9833333333333333

In [6]:
rf = RandomForestClassifier(n_estimators = 50)
rf.fit(xtrain, ytrain)
rf.score(xtest, ytest)

0.9740740740740741

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8]):
    print(train_index, test_index)

[2 3 4 5 6 7] [0 1]
[0 1 4 5 6 7] [2 3]
[0 1 2 3 6 7] [4 5]
[0 1 2 3 4 5] [6 7]


In [9]:
def getscore(model, xtrain, xtest, ytrain, ytest):
    model.fit(xtrain, ytrain)
    return model.score(xtest, ytest)

In [10]:
getscore(SVC(), xtrain, xtest, ytrain, ytest)

0.9833333333333333

In [11]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 4)

In [22]:
scorel = []
scoresvm = []
scorerf = []

### Behind the scenes for K fold validation

In [23]:
for train_index, test_index in kf.split(digits.data):
    xtrain, xtest, ytrain, ytest = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scorel.append(getscore(LogisticRegression(), xtrain, xtest, ytrain, ytest))
    scoresvm.append(getscore(SVC(), xtrain, xtest, ytrain, ytest))
    scorerf.append(getscore(RandomForestClassifier(n_estimators = 10), xtrain, xtest, ytrain, ytest))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [24]:
scorel

[0.9355555555555556,
 0.9153674832962138,
 0.9510022271714922,
 0.9175946547884187]

In [25]:
scoresvm

[0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [26]:
scorerf

[0.9066666666666666,
 0.8552338530066815,
 0.9487750556792873,
 0.9042316258351893]

### K fold validation

In [27]:
from sklearn.model_selection import cross_val_score

In [28]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [29]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators = 10), digits.data, digits.target)

array([0.89166667, 0.85555556, 0.93036212, 0.92479109, 0.87743733])

## K Fold Cross Validation on IRIS DATASET

In [33]:
from sklearn.datasets import load_iris

In [34]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [44]:
import numpy as np

In [45]:
skf = StratifiedKFold(n_splits = 3)

In [46]:
lreg = cross_val_score(LinearRegression(), iris.data, iris.target)
lreg

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [47]:
np.average(lreg)

0.3225607248900085

In [48]:
logreg = cross_val_score(LogisticRegression(), iris.data, iris.target)
logreg

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [49]:
np.average(logreg)

0.9733333333333334

In [50]:
svmscore = cross_val_score(SVC(), iris.data, iris.target)
svmscore

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [51]:
np.average(svmscore)

0.9666666666666666

In [56]:
rfc = cross_val_score(RandomForestClassifier(n_estimators = 20), iris.data, iris.target)
rfc

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [57]:
np.average(rfc)

0.96

In [54]:
dtc = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dtc

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [55]:
np.average(dtc)

0.9600000000000002

#### Best score is given by Logistic Regression , then SVM, Decision Tree, Random Forest