In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [9]:
df = pd.read_csv('homeprices3.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### replace nan values in given data with median

In [10]:
import math
median_bedrm = math.floor(df.bedrooms.median())
median_bedrm

4

In [12]:
df.bedrooms = df.bedrooms.fillna(median_bedrm)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg = LinearRegression()
reg.fit(df[['area', 'bedrooms','age']], df.price)

LinearRegression()

In [15]:
reg.predict([[4100, 6,2]])

array([814648.85847853])

In [16]:
reg.score(df[['area', 'bedrooms','age']], df.price)

0.9550196399325818

## Homework Question

In [17]:
df1 = pd.read_csv('hiring3.csv')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
import math
median_testscore = math.floor(df1['test_score(out of 10)'].median())
median_testscore

8

In [20]:
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(median_testscore)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [22]:
from word2number import w2n

In [23]:
df1.experience = df1.experience.fillna('zero')
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [26]:
reg1 = LinearRegression()

In [27]:
reg1.fit(df1[['experience','test_score(out of 10)', 'interview_score(out of 10)']], df1['salary($)'])

LinearRegression()

In [28]:
reg1.predict([[2,9,6]])

array([53205.96797671])

In [29]:
reg1.predict([[12,10,10]])

array([92002.18340611])

In [30]:
reg1.score(df1[['experience','test_score(out of 10)', 'interview_score(out of 10)']], df1['salary($)'])

0.9616780002577958